import Head from "next/head";
import {PatientManagementPage} from "@/pages/user/simulation/simulation-cases/patient-management-page";
import HeroSimulation from "@/components/organism/hero-simulation";
import Navbar from "@/components/organism/navbar-registered";
import {Footer} from "@/components/organism/footer";

export default function Simulasi() {
    return (
        <>
            <Head>
                <title>Open MRI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeroSimulation />
            <PatientManagementPage />
            <Footer />
        </>
    );
}
