import Head from "next/head";
import ForgotPassword from "@/components/template/forgot-password/forgot-password"

export default function FGTPassworD(){
    return (
        <>
            <Head>
                <title>Forgot Password</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ForgotPassword/>
        </>
    )
}