import Head from "next/head";
import Skenariotpprj from "@/components/template/admin/page-skenario/Skenario-tpprj";  
export default function Home() {
    return (
        <>
            <Head>
                <title>Skenario TPPGD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Skenariotpprj/>
        </>
    );
}
