import Head from "next/head";
import EditFormSimulasiTppri from "@/components/template/admin/edit-form-simulasi/edit-form-tppri";  
export default function Home() {
    return (
        <>
            <Head>
                <title>Edit Form Simulasi TPPRI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <EditFormSimulasiTppri/>
        </>
    );
}
