import Head from "next/head";
import PatientDetailPage from "@/pages/user/simulation/simulation-detail-case/patient-detail";
import HeroSimulation from "@/components/organism/hero-simulation";
import Navbar from "@/components/organism/navbar-registered";
import {Footer} from "@/components/organism/footer";

export default function SimulationDetail() {
    return (
        <>
            <Head>
                <title>Detail Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <HeroSimulation />
            <PatientDetailPage />
            <Footer />
        </>
    );
}
