import Head from "next/head";
import ShowSimulasittpri from "@/components/template/admin/page-show-simulasi/simulasi-tppri";  
export default function Home() {
    return (
        <>
            <Head>
                <title>Detail Simulasi TPPRI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ShowSimulasittpri/>
        </>
    );
}