import Head from "next/head";
import ResetPassword from "@/components/template/forgot-password/reset-password"

export default function RstPPassword(){
    return (
        <>
            <Head>
                <title>Reset Password</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ResetPassword />
        </>
    )
}