import Head from "next/head";
// import HeroSimulation from "@/components/organism/hero-simulation";
import Navbar from "@/components/organism/navbar-registered";
import {Footer} from "@/components/organism/footer";
import SimulationDetailCase from "./patient-simulation";

export default function Simulasi() {
    return (
        <>
            <Head>
                <title>Open MRI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            {/* <HeroSimulation /> */}
            <SimulationDetailCase />
            <Footer />
        </>
    );
}
