import Head from "next/head";
import FormSkenarioTppgd from "@/components/template/admin/form-skenario/form-tppgd";  
export default function Home() {
    return (
        <>
            <Head>
                <title>Form Skenario TPPGD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FormSkenarioTppgd/>
        </>
    );
}