"use client";

import {Footer} from "@/components/organism/footer";
import Navbar from "@/components/organism/navbar-registered";
import {ProfileTemplate} from "@/components/template/user/profile/profile";
import Head from "next/head";

export default function ProfilePage() {
    return (
        <>
            <Head>
                <title>Open MRI</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <ProfileTemplate />;
            <Footer />
        </>
    );
}
