import Head from "next/head";
import Simulasittpgd from "@/components/template/admin/page-simulasi/Simulasi-tppgd";  
export default function Home() {
    return (
        <>
            <Head>
                <title>Simulasi TPPGD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Simulasittpgd/>
        </>
    );
}
